# Use phusion/baseimage as base image. To make your builds
# reproducible, make sure you lock down to a specific version, not
# to `latest`! See
# https://github.com/phusion/baseimage-docker/blob/master/Changelog.md
# for a list of version numbers.
FROM registry.jeshkov.ru:5000/customers/solve.me/solve.me:devsrc1
ENV DEBIAN_FRONTEND noninteractive

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# ...put your own build instructions here...

# Clean up APT when done.

RUN rm -rf /var/www/html
ADD . /var/www
RUN ln -s /var/www/public /var/www/html && mkdir /var/www/.composer && chown -R www-data /var/www/ && mkdir /etc/service/apache
USER www-data
ARG branch
RUN cd /var/www/ && cp .env.$branch .env && rm -rf node_modules && composer install && npm install  --no-save  && npm run dev
#RUN cd /var/www/ && php artisan migrate

#RUN cd /var/www/ && ./vendor/bin/phpunit tests && make init
USER root
COPY ci/authorized_keys /root/.ssh/
COPY ci/000-default.conf /etc/apache2/sites-enabled/
COPY ci/apache.sh /etc/service/apache/run
RUN chmod 600 /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && touch /var/www/storage/logs/laravel.log && chown -R www-data:www-data /var/www/storage && chmod -R 777 /var/www/storage \
    && chmod +x /etc/service/apache/run && a2enmod rewrite && rm -f /etc/service/sshd/down && /etc/my_init.d/00_regen_ssh_host_keys.sh




